config/routes.rb
Rails.application.routes.draw do



  resources :selfie_verifications, :except => [:index, :destroy]
  resources :address_verifications, :except => [:index, :destroy]
  resources :nationalid_verifications, :except => [:index, :destroy]
  resources :user_infos, :only => [:show, :create, :update]
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
      # resources :cards
      get "buy_card" => "cards#buy_card" 
      # resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :addresses
      get "user_addresses" => "addresses#user_addresses"
      resources :user_wallets
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms" 
      get "user_wallet_balance" => "user_wallets#user_wallet_balance"
      resources :notifications
      resources :notifications_settings
      get "user_notifications" => "notifications#user_notifications"
      get "search_notifications" => "notifications#search"
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :uploads
    end
  end



  resources :affilate_programs, :only => [:create, :destroy]
  resources :countries, :only => [:index, :show]
  resources :logins, :only => [:create, :show, :destroy]
  resources :verifications, :only => [:create, :update, :destroy]
  resources :watchdogs, :only => [:create, :show, :destroy]
  resources :users, :except => [:index]
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "change_confirmation_code" => "users#change_confirmation_code"
  get "confirm_google_code" => "users#confirm_google_code"
  # get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:refered_by" => "affilate_programs#set_invitation_code"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "error_page" => "logins#error_page"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  # resources :cards
  get "buy_card" => "cards#buy_card"
  get "user_cards" => "cards#user_cards"
  get "remittance" => "cards#remittance"
  get "payment_method" => "cards#payment_method"
  get "payment_data" => "cards#payment_data"
  # resources :cards_categories
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  resources :addresses
  get "user_addresses" => "addresses#user_addresses"
  resources :user_wallets
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "user_wallet_balance" => "user_wallets#user_wallet_balance"
  resources :notifications
  resources :notifications_settings
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  get "user_notifications_setting" => "notifications_settings#user_notifications_setting"
  resources :uploads
  get "destroy_all_sessions" => "clearance/sessions#destroy_all_sessions"
  get "destroy_one_session" => "clearance/sessions#destroy_one_session"
  #match '*path', to: "logins#error_page", via: :all



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/upload.rb
class Upload < ApplicationRecord
    has_one_attached :avatar

    def image_file=(avatar)
        self.image_file.attach(avatar)
    end 

    
end

app/controllers/api/v1/uploads_controller.rb
module Api
  module V1
    class UploadsController < ApplicationController
      before_action :set_upload, only: [:show, :edit, :update, :destroy]
      skip_before_action :verify_authenticity_token


      # GET /uploads
      # GET /uploads.json
      def index
        @uploads = Upload.all
      end

      # GET /uploads/1
      # GET /uploads/1.json
      def show
      end

      # GET /uploads/new
      def new
        @upload = Upload.new
      end

      # GET /uploads/1/edit
      def edit
      end

      # POST /uploads
      # POST /uploads.json
      def image_status

        # @attachment = Upload.where(:id => params[:id].to_i).first
        #    if  current_user = session[:user_id]
        #      @data_url = @attachment.avatar.service_url
            
        #      require 'open-uri'
        #      open('image.png', 'wb') do |file|
        #        @the_file = file << open(@data_url).read
        #        send_file @the_file
        #      end
            
        #      else

        #      redirect_to(login_path,:notice => "صوره غير مسموح لك  بها")
        #    end

      end

      def create
        
        @file_name = image_upload
        @upload = Upload.create(:title => params[:upload][:title],:user_id => current_user.id.to_i)
        @upload.avatar.attach(io: File.open(@file_name), filename: @file_name, content_type: "image/jpg")

        # @upload = Upload.new(upload_params)
        respond_to do |format|

          if @upload
            format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
            format.json { render :show, status: :created, location: @upload }
          else
            format.html { render :new }
            format.json { render json: @upload.errors, status: :unprocessable_entity }
          end

        end

      end

      # PATCH/PUT /uploads/1
      # PATCH/PUT /uploads/1.json
      def update

        @file_name = image_upload
        @upload_update = @upload.update(:title => params[:upload][:title])
        @upload.avatar.attach(io: File.open(@file_name), filename: @file_name, content_type: "image/jpg")

        respond_to do |format|
          if @upload_update
            format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
            format.json { render :show, status: :ok, location: @upload }
          else
            format.html { render :edit }
            format.json { render json: @upload.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /uploads/1
      def destroy
        @upload.destroy
        respond_to do |format|
          flash[:success] = "Upload was successfully deleted"
          format.json { render json: flash }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_upload
          @upload = Upload.find(params[:id])
        end

        def image_upload
          @avatar = params[:upload][:avatar]
          @image_data = ActiveSupport::JSON.decode(@avatar)
          @data_im = @image_data['output']['image']
      
          require 'mime/types'
          @REGEXP = /\Adata:([-\w]+\/[-\w\+\.]+)?;base64,(.*)/m
      
          data_uri_parts = @data_im.match(@REGEXP) || []
          extension = MIME::Types[data_uri_parts[1]].first.preferred_extension
          rand_id = rand 100000..999999
          @file_name = "#{rand_id}.#{extension}"
          @bb = File.open(@file_name, 'wb') do |file|
            @aa= file.write(Base64.decode64(data_uri_parts[2]))
          end
          
          return @file_name
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def upload_params
          params.require(:upload).permit(:title,:user_id)
        end
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.where(user_id: current_user.id.to_i).all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end


  def create
    
    @file_name = image_upload
    @upload = Upload.create(:title => params[:upload][:title],:user_id => current_user.id.to_i)
    @upload.avatar.attach(io: File.open(@file_name), filename: @file_name, content_type: "image/jpg")

    # @upload = Upload.new(upload_params)
    respond_to do |format|

      if @upload
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end

    end

  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update

    @file_name = image_upload
    @upload_update = @upload.update(:title => params[:upload][:title])
    @upload.avatar.attach(io: File.open(@file_name), filename: @file_name, content_type: "image/jpg")

    respond_to do |format|
      if @upload_update
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.where(user_id: current_user.id.to_i, id: params[:id]).first
    end

    def image_upload
      @avatar = params[:upload][:avatar]
      @image_data = ActiveSupport::JSON.decode(@avatar)
      @data_im = @image_data['output']['image']
  
      require 'mime/types'
      @REGEXP = /\Adata:([-\w]+\/[-\w\+\.]+)?;base64,(.*)/m
  
      data_uri_parts = @data_im.match(@REGEXP) || []
      extension = MIME::Types[data_uri_parts[1]].first.preferred_extension
      rand_id = rand 100000..999999
      @file_name = "#{rand_id}.#{extension}"
      @bb = File.open(@file_name, 'wb') do |file|
        @aa= file.write(Base64.decode64(data_uri_parts[2]))
      end
      
      return @file_name
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:title,:user_id)
    end
end

app/views/uploads/_form.html.erb
<link rel="stylesheet" href="/css/slim.min.css">

<style>
        /* center main column */
        main {
          font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;
            max-width:400px;
            margin:0 auto;
        }
    </style>
<main>

    
<%= form_with(model: upload, local: true) do |form| %>
  <% if upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div><br>

  <div class="slim" >
    <%= form.file_field :avatar, direct_upload: true %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</main>
<script src="/js/slim.kickstart.min.js"></script>

app/views/uploads/create.html.erb
<%= debug(@bb)%>
<%= debug(@aa)%>

app/views/uploads/edit.html.erb
<link rel="stylesheet" href="/css/slim.min.css">

<style>
        /* center main column */
        main {
          font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;
            max-width:400px;
            margin:0 auto;
        }
    </style>
<main>

<h1>Editing Upload</h1>
    
<%= form_with(model: @upload, local: true) do |form| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div><br>

  <div class="slim" >
  <%= link_to image_tag(@upload.avatar), @upload.avatar %>
    <%= form.file_field :avatar, direct_upload: true %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', uploads_path %> |
<%= link_to 'Show', @upload %> |
<%= link_to 'New Upload', new_upload_path %>

</main>
<script src="/js/slim.kickstart.min.js"></script>

app/views/uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uploads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.title %></td>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<link rel="stylesheet" href="/css/slim.min.css">

<style>
        /* center main column */
        main {
          font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;
            max-width:400px;
            margin:0 auto;
        }
    </style>
<main>
<h1>New Upload</h1>
    
<%= form_with(model: @upload, local: true) do |form| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div><br>

  <div class="slim" >
    <%= form.file_field :avatar, direct_upload: true %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<br>
<%= link_to 'Back', uploads_path %> |

<%= link_to 'New Upload', new_upload_path %>
</main>
<script src="/js/slim.kickstart.min.js"></script>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @upload.title %>
</p>

<%= link_to image_tag(@upload.avatar), @upload.avatar %>
<br>
<%= link_to 'Edit', edit_upload_path(@upload) %> ||
<%= link_to 'Back', uploads_path %><br>